Rest/Rest-war/src/java/FuncionarioMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import ejb.Funcionario;
import ejb.FuncionarioFachada;
import java.util.List;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;

/**
 *
 * @author Caio
 */
@Named(value = "funcionarioMBean")
@RequestScoped
public class FuncionarioMBean {

    @EJB
    private FuncionarioFachada funcionarioFachada;

    /**
     * Creates a new instance of FuncionarioMBean
     */
    public FuncionarioMBean() {
    }
    
     public List<Funcionario> getListaFuncionarios() {
        return funcionarioFachada.getListaFuncionarios();
    }
    
}

Rest/Rest-war/web/index.xhtml
<f:view xmlns:p="http://primefaces.org/ui" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:form>
        <h1><h:outputText value="Lista de Funcionarios"/></h1>
        <p:dataTable var="funcionario" value="#{funcionarioMBean.listaFuncionarios}">
            <p:column headerText="Id">
                <h:outputText value="#{funcionario.id_funcionario}" />
            </p:column>
            <p:column headerText="Nome">
                <h:outputText value="#{funcionario.nome}" /> 
            </p:column>
            <p:column headerText="CPF">
                <h:outputText value="#{funcionario.cpf}" />
            </p:column>
        </p:dataTable>
    </h:form>
</f:view>